import { Avatar } from "@mui/material";
import { auth } from "../../auth";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  var session = await auth()

  return (
    <html lang="en">
      <body>
        <div className="flex justify-end">
          {session?.user?.name ? <Avatar className="block mt-3 mr-3" src={session?.user?.image}></Avatar> : <></>}
        </div>
        {children}
      </body>
    </html>
  );
}
